#!/bin/bash
# COLOUR MENU UTAMA
NC='\033[0;34m'
p='\033[0;37m'
CYAN='\033[0;36m'
YELL='\033[1;33m'
clear
mkdir -p /etc/abcde
echo -e ""
echo -e " ${NC} ╭════════════════════════════════════════════════════════════╮"
echo -e " ${NC} │${p}                      COLOUR                               ${NC}"
echo -e " ${NC} ╰════════════════════════════════════════════════════════════╯"
echo -e " ${NC} ╭════════════════════════════════════════════════════════════╮"
echo -e " ${NC} │${p} 01. 🔴🟣🟡🟢 ${NC}"
echo -e " ${NC} │${p} 02. 🟡🟣🟢🟤 ${NC}"
echo -e " ${NC} │${p} 03. 🔵🟢🟡⚪ ${NC}"
echo -e " ${NC} │${p} 04. 🟣🔵🟢⚪ ${NC}"
echo -e " ${NC} │${p} 05. 🟢🔵🟣🟡 ${NC}"
echo -e " ${NC} │${p} 06. 🔴🟡⚪🔵 ${NC}"
echo -e " ${NC} │${p} 07. 🟤🟡🟢🔵 ${NC}"
echo -e " ${NC} │${p} 08. ⚪🔵🟢🟣 ${NC}"
echo -e " ${NC} │${p} 09. 🟢⚪🔴🟡 ${NC}"
echo -e " ${NC} │${p} 10. 🔵🟣⚪🟢 ${NC}"
echo -e " ${NC} │${p} 11. 🟡🔴🔵⚪ ${NC}"
echo -e " ${NC} │${p} 12. 🟣🟢🔴⚪ ${NC}"
echo -e " ${NC} │${p} 13. ⚪🟡🟣🔵 ${NC}"
echo -e " ${NC} │${p} 14. 🔴🔵⚪🟢 ${NC}"
echo -e " ${NC} │${p} 15. 🟢🟡🔵🟣 ${NC}"
echo -e " ${NC} │${p} 16. 🔵⚪🟡🔴 ${NC}"
echo -e " ${NC} │${p} 17. 🟣⚪🟢🟡 ${NC}"
echo -e " ${NC} │${p} 18. 🟡🟢🔴🔵 ${NC}"
echo -e " ${NC} │${p} 19. ⚪🟣🔵🟢 ${NC}"
echo -e " ${NC} │${p} 20. 🔴⚪🟢🟣 ${NC}"
echo -e " ${NC} │${p} 21. 🟢🔴🟡⚪ ${NC}"
echo -e " ${NC} │${p} 22. 🔵🟡🟣🟢 ${NC}"
echo -e " ${NC} │${p} 23. 🟣🔴⚪🔵 ${NC}"
echo -e " ${NC} │${p} 24. 🟡⚪🔵🟢 ${NC}"
echo -e " ${NC} │${p} 25. ⚪🟢🟣🔴 ${NC}"
echo -e " ${NC} ╰════════════════════════════════════════════════════════════╯"
echo -e ""
read -p "  Options [ 1 - 25 ] ❱❱❱ " opt
case "$opt" in
1)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;31m'
CYAN='\033[1;35m'
YELL='\033[1;33m'
p='\033[1;32m'
green='\033[1;33m'
GREEN='\033[1;33m'
RED='\033[1;31m'
BLUE='\033[1;35m'
Blue='\033[1;35m'
blue='\033[1;35m'
purple='\033[1;35m'
LIGHT='\033[1;32m'
hijau='\033[1;33m'
EOF
;;
2)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;33m'
CYAN='\033[1;35m'
YELL='\033[1;32m'
p='\033[1;33m'
green='\033[1;32m'
GREEN='\033[1;32m'
RED='\033[1;33m'
BLUE='\033[1;35m'
Blue='\033[1;35m'
blue='\033[1;35m'
purple='\033[1;35m'
LIGHT='\033[1;33m'
hijau='\033[1;32m'
EOF
;;
3)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;34m'
CYAN='\033[1;32m'
YELL='\033[1;33m'
p='\033[1;37m'
green='\033[1;33m'
GREEN='\033[1;33m'
RED='\033[1;34m'
BLUE='\033[1;32m'
Blue='\033[1;32m'
blue='\033[1;32m'
purple='\033[1;32m'
LIGHT='\033[1;37m'
hijau='\033[1;33m'
EOF
;;
4)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;35m'
CYAN='\033[1;34m'
YELL='\033[1;32m'
p='\033[1;37m'
green='\033[1;32m'
GREEN='\033[1;32m'
RED='\033[1;35m'
BLUE='\033[1;34m'
Blue='\033[1;34m'
blue='\033[1;34m'
purple='\033[1;34m'
LIGHT='\033[1;37m'
hijau='\033[1;32m'
EOF
;;
5)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;32m'
CYAN='\033[1;34m'
YELL='\033[1;35m'
p='\033[1;33m'
green='\033[1;35m'
GREEN='\033[1;35m'
RED='\033[1;32m'
BLUE='\033[1;34m'
Blue='\033[1;34m'
blue='\033[1;34m'
purple='\033[1;34m'
LIGHT='\033[1;33m'
hijau='\033[1;35m'
EOF
;;
6)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;31m'
CYAN='\033[1;33m'
YELL='\033[1;37m'
p='\033[1;34m'
green='\033[1;37m'
GREEN='\033[1;37m'
RED='\033[1;31m'
BLUE='\033[1;33m'
Blue='\033[1;33m'
blue='\033[1;33m'
purple='\033[1;33m'
LIGHT='\033[1;34m'
hijau='\033[1;37m'
EOF
;;
7)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;33m'
CYAN='\033[1;33m'
YELL='\033[1;32m'
p='\033[1;34m'
green='\033[1;32m'
GREEN='\033[1;32m'
RED='\033[1;33m'
BLUE='\033[1;33m'
Blue='\033[1;33m'
blue='\033[1;33m'
purple='\033[1;33m'
LIGHT='\033[1;34m'
hijau='\033[1;32m'
EOF
;;
8)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;37m'
CYAN='\033[1;34m'
YELL='\033[1;32m'
p='\033[1;35m'
green='\033[1;32m'
GREEN='\033[1;32m'
RED='\033[1;37m'
BLUE='\033[1;34m'
Blue='\033[1;34m'
blue='\033[1;34m'
purple='\033[1;34m'
LIGHT='\033[1;35m'
hijau='\033[1;32m'
EOF
;;
9)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;32m'
CYAN='\033[1;37m'
YELL='\033[1;31m'
p='\033[1;33m'
green='\033[1;31m'
GREEN='\033[1;31m'
RED='\033[1;32m'
BLUE='\033[1;37m'
Blue='\033[1;37m'
blue='\033[1;37m'
purple='\033[1;37m'
LIGHT='\033[1;33m'
hijau='\033[1;31m'
EOF
;;
10)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;34m'
CYAN='\033[1;35m'
YELL='\033[1;37m'
p='\033[1;32m'
green='\033[1;37m'
GREEN='\033[1;37m'
RED='\033[1;34m'
BLUE='\033[1;35m'
Blue='\033[1;35m'
blue='\033[1;35m'
purple='\033[1;35m'
LIGHT='\033[1;32m'
hijau='\033[1;37m'
EOF
;;
11)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;33m'
CYAN='\033[1;31m'
YELL='\033[1;34m'
p='\033[1;37m'
green='\033[1;34m'
GREEN='\033[1;34m'
RED='\033[1;33m'
BLUE='\033[1;31m'
Blue='\033[1;31m'
blue='\033[1;31m'
purple='\033[1;31m'
LIGHT='\033[1;37m'
hijau='\033[1;34m'
EOF
;;
12)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;35m'
CYAN='\033[1;32m'
YELL='\033[1;31m'
p='\033[1;37m'
green='\033[1;31m'
GREEN='\033[1;31m'
RED='\033[1;35m'
BLUE='\033[1;32m'
Blue='\033[1;32m'
blue='\033[1;32m'
purple='\033[1;32m'
LIGHT='\033[1;37m'
hijau='\033[1;31m'
EOF
;;
13)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;37m'
CYAN='\033[1;33m'
YELL='\033[1;35m'
p='\033[1;34m'
green='\033[1;35m'
GREEN='\033[1;35m'
RED='\033[1;37m'
BLUE='\033[1;33m'
Blue='\033[1;33m'
blue='\033[1;33m'
purple='\033[1;33m'
LIGHT='\033[1;34m'
hijau='\033[1;35m'
EOF
;;
14)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;31m'
CYAN='\033[1;34m'
YELL='\033[1;37m'
p='\033[1;32m'
green='\033[1;37m'
GREEN='\033[1;37m'
RED='\033[1;31m'
BLUE='\033[1;34m'
Blue='\033[1;34m'
blue='\033[1;34m'
purple='\033[1;34m'
LIGHT='\033[1;32m'
hijau='\033[1;37m'
EOF
;;
15)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;32m'
CYAN='\033[1;33m'
YELL='\033[1;34m'
p='\033[1;35m'
green='\033[1;34m'
GREEN='\033[1;34m'
RED='\033[1;32m'
BLUE='\033[1;33m'
Blue='\033[1;33m'
blue='\033[1;33m'
purple='\033[1;33m'
LIGHT='\033[1;35m'
hijau='\033[1;34m'
EOF
;;
16)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;34m'
CYAN='\033[1;37m'
YELL='\033[1;33m'
p='\033[1;31m'
green='\033[1;33m'
GREEN='\033[1;33m'
RED='\033[1;34m'
BLUE='\033[1;37m'
Blue='\033[1;37m'
blue='\033[1;37m'
purple='\033[1;37m'
LIGHT='\033[1;31m'
hijau='\033[1;33m'
EOF
;;
17)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;35m'
CYAN='\033[1;37m'
YELL='\033[1;32m'
p='\033[1;33m'
green='\033[1;32m'
GREEN='\033[1;32m'
RED='\033[1;35m'
BLUE='\033[1;37m'
Blue='\033[1;37m'
blue='\033[1;37m'
purple='\033[1;37m'
LIGHT='\033[1;33m'
hijau='\033[1;32m'
EOF
;;
18)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;33m'
CYAN='\033[1;32m'
YELL='\033[1;31m'
p='\033[1;34m'
green='\033[1;31m'
GREEN='\033[1;31m'
RED='\033[1;33m'
BLUE='\033[1;32m'
Blue='\033[1;32m'
blue='\033[1;32m'
purple='\033[1;32m'
LIGHT='\033[1;34m'
hijau='\033[1;31m'
EOF
;;
19)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;37m'
CYAN='\033[1;35m'
YELL='\033[1;34m'
p='\033[1;32m'
green='\033[1;34m'
GREEN='\033[1;34m'
RED='\033[1;37m'
BLUE='\033[1;35m'
Blue='\033[1;35m'
blue='\033[1;35m'
purple='\033[1;35m'
LIGHT='\033[1;32m'
hijau='\033[1;34m'
EOF
;;
20)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;31m'
CYAN='\033[1;37m'
YELL='\033[1;32m'
p='\033[1;35m'
green='\033[1;32m'
GREEN='\033[1;32m'
RED='\033[1;31m'
BLUE='\033[1;37m'
Blue='\033[1;37m'
blue='\033[1;37m'
purple='\033[1;37m'
LIGHT='\033[1;35m'
hijau='\033[1;32m'
EOF
;;
21)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;32m'
CYAN='\033[1;31m'
YELL='\033[1;33m'
p='\033[1;37m'
green='\033[1;33m'
GREEN='\033[1;33m'
RED='\033[1;32m'
BLUE='\033[1;31m'
Blue='\033[1;31m'
blue='\033[1;31m'
purple='\033[1;31m'
LIGHT='\033[1;37m'
hijau='\033[1;33m'
EOF
;;
22)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;34m'
CYAN='\033[1;33m'
YELL='\033[1;35m'
p='\033[1;32m'
green='\033[1;35m'
GREEN='\033[1;35m'
RED='\033[1;34m'
BLUE='\033[1;33m'
Blue='\033[1;33m'
blue='\033[1;33m'
purple='\033[1;33m'
LIGHT='\033[1;32m'
hijau='\033[1;35m'
EOF
;;
23)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;35m'
CYAN='\033[1;31m'
YELL='\033[1;37m'
p='\033[1;34m'
green='\033[1;37m'
GREEN='\033[1;37m'
RED='\033[1;35m'
BLUE='\033[1;31m'
Blue='\033[1;31m'
blue='\033[1;31m'
purple='\033[1;31m'
LIGHT='\033[1;34m'
hijau='\033[1;37m'
EOF
;;
24)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;33m'
CYAN='\033[1;37m'
YELL='\033[1;34m'
p='\033[1;32m'
green='\033[1;34m'
GREEN='\033[1;34m'
RED='\033[1;33m'
BLUE='\033[1;37m'
Blue='\033[1;37m'
blue='\033[1;37m'
purple='\033[1;37m'
LIGHT='\033[1;32m'
hijau='\033[1;34m'
EOF
;;
25)
cat >/etc/abcde/menu-color.conf <<'EOF'
NC='\033[1;37m'
CYAN='\033[1;32m'
YELL='\033[1;35m'
p='\033[1;31m'
green='\033[1;35m'
GREEN='\033[1;35m'
RED='\033[1;37m'
BLUE='\033[1;32m'
Blue='\033[1;32m'
blue='\033[1;32m'
purple='\033[1;32m'
LIGHT='\033[1;31m'
hijau='\033[1;35m'
EOF
;;
0|00|x|X)
    menu
    exit 0
;;
*)
    echo -e " Pilihan tidak valid"
    sleep 1
    change-color
    exit 0
;;
esac
echo -e ""
echo -e " Berhasil disimpan."
sleep 1
menu
